### ISSUE TITLE
Google Analytics: Need to figure out why no one is clicking on the donation page

### ISSUE THREAD

**Issue by meghaghildyal** [spring-giant/mgt656-spring-2015-project#58]

**Comment by meghaghildyal** [comment]
everyone in the class facing this problem right now...kyle mentioned it in class as well that its a code issue

**Comment by meghaghildyal** [comment]
TA to resolve in class on Monday-they can't figure out with our account as of now (have been talking to them on e-mail)

**Comment by peapumpkin** [comment]
So I had to look at the donation code for the A/B test, and it looks like the way it is set up on the event detail page is not a redirect to the donation page but rather part of the RSVP email input form. I played around with changing it so it could work for the a/b test...there are several options but for now I have: <a href="/donate"<button type="button" class="btn btn-danger">Donate here</button></a>

**Comment by meghaghildyal** [comment]
Lea, nothing happens when i click on the link you've posted. i'll take this up with the TAs tomorrow

**Comment by meghaghildyal** [comment]
this did redirect to a 'donate' page earlier. I am not sure why this has changed now? very strange..the page i created is called donation.html and exists in cloud 9

**Comment by jeffmcq1616** [comment]
I think I fixed it--should I commit the changes?

**Comment by meghaghildyal** [comment]
yes please.. i will undo the changes i have been making so it doesnt clash with yours

**Comment by jeffmcq1616** [comment]
Just made the pull request. Take a look at it.

**Comment by meghaghildyal** [comment]
aah.. closing form tag got deleted? </form>? pushed new changes

**Comment by meghaghildyal** [comment]
tried double class, didn't work.
changed donate button to a link, still dont see any results in analytics (after clicking on donate here myself on heroku..will talk to David after class
comment code"<a href="/donate" class="donation"><p style="color:blue; font-family:comic sans ms;"><font size="6"><b>"Donate Here..."</b></font></p></a>"

**Comment by meghaghildyal** [comment]
working now after extending  layout.html to donate page. see analytics under behaviour-->overview-->view full report-->search 'donate'
